// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfw0Xnm30I0_f2IRnVNyk-wXgEZrLGF74',
    appId: '1:863686671931:web:7211797523c9f8a457e61e',
    messagingSenderId: '863686671931',
    projectId: 'fir-register-page-caa6f',
    authDomain: 'fir-register-page-caa6f.firebaseapp.com',
    storageBucket: 'fir-register-page-caa6f.appspot.com',
    measurementId: 'G-MZVBWK4RR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKqn_CBxLAxDMxOVMCJDaly64ajh7BR04',
    appId: '1:863686671931:android:5a81d17732a3dd2657e61e',
    messagingSenderId: '863686671931',
    projectId: 'fir-register-page-caa6f',
    storageBucket: 'fir-register-page-caa6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmTA7TfTDV859WmW-IZ_LWxjefBoNPSs',
    appId: '1:863686671931:ios:4a6d8e3f867b22e557e61e',
    messagingSenderId: '863686671931',
    projectId: 'fir-register-page-caa6f',
    storageBucket: 'fir-register-page-caa6f.appspot.com',
    iosBundleId: 'com.example.faerbasRegisterPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEmTA7TfTDV859WmW-IZ_LWxjefBoNPSs',
    appId: '1:863686671931:ios:129dec4a5276b4ff57e61e',
    messagingSenderId: '863686671931',
    projectId: 'fir-register-page-caa6f',
    storageBucket: 'fir-register-page-caa6f.appspot.com',
    iosBundleId: 'com.example.faerbasRegisterPage.RunnerTests',
  );
}
